=== MasterNomad/EPAM_lab_XML/data/products.xsd
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="products">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="category" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subcategory" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="product" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="brand">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="ACER"/>
                                                                <xs:enumeration value="DELL"/>
                                                                <xs:enumeration value="HP"/>
                                                                <xs:enumeration value="ASUS"/>
                                                                <xs:enumeration value="DLINK"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element type="xs:string" name="model"/>
                                                    <xs:element type="xs:date" name="dateOfManufacture"/>
                                                    <xs:element name="color">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="BLACK"/>
                                                                <xs:enumeration value="WHITE"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element type="xs:decimal" name="price"/>
                                                    <xs:element type="xs:integer" name="quantity" maxOccurs="unbounded" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="title" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:integer" name="id" use="required"/>
                        <xs:attribute type="xs:string" name="title" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MasterNomad/EPAM_lab_XML/data/products.xml
<?xml version="1.0" encoding="utf-8"?>

<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="products.xsd">
    <category id ="1" title = "Компьютеры и периферия">
        <subcategory title = "Системные блоки">
            <product>
                <brand>DELL</brand>
                <model>SF347</model>
                <dateOfManufacture>2019-04-21</dateOfManufacture>
                <color>BLACK</color>
                <price>25799</price>
                <quantity>4</quantity>
            </product>
            <product>
                <brand>HP</brand>
                <model>ur460</model>
                <dateOfManufacture>2019-02-21</dateOfManufacture>
                <color>BLACK</color>
                <price>17999</price>
                <quantity>2</quantity>
            </product>
        </subcategory>
        <subcategory title = "Мониторы">
            <product>
                <brand>ASUS</brand>
                <model>VS197</model>
                <dateOfManufacture>2019-04-01</dateOfManufacture>
                <color>BLACK</color>
                <price>4499</price>
                <quantity>1</quantity>
            </product>
            <product>
                <brand>ACER</brand>
                <model>ET241</model>
                <dateOfManufacture>2019-02-21</dateOfManufacture>
                <color>BLACK</color>
                <price>7850</price>
                <quantity>8</quantity>
            </product>
        </subcategory>
    </category>
       <category id ="2" title = "Сетевое оборудование">
        <subcategory title = "Маршрутизаторы ">
            <product>
                <brand>ASUS</brand>
                <model>rt120</model>
                <dateOfManufacture>2018-04-21</dateOfManufacture>
                <color>BLACK</color>
                <price>3099</price>
                <quantity>20</quantity>
            </product>
            <product>
                <brand>DLINK</brand>
                <model>LA640</model>
                <dateOfManufacture>2019-01-15</dateOfManufacture>
                <color>WHITE</color>
                <price>4199</price>
                <quantity>9</quantity>
            </product>
        </subcategory>
        <subcategory title = "Wi-Fi оборудование">
            <product>
                <brand>DLINK</brand>
                <model>DW548</model>
                <dateOfManufacture>2017-03-18</dateOfManufacture>
                <color>BLACK</color>
                <price>950</price>
                <quantity>19</quantity>
            </product>
        </subcategory>
    </category>
</products>
